version: '3.8'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: equip-nginx
    ports:
      - 8080:80
    volumes:
      - ./back/src:/var/www/laravel_docker
      - ./back/nginx:/etc/nginx/conf.d
    networks:
      - hotel_net

  php-fpm:
    container_name: hotel-php-fpm
    build:
      context: back/php
    ports:
      - "9000:9000"
    working_dir: /var/www/laravel_docker
    volumes:
      - ./back/src:/var/www/laravel_docker
    environment:
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILESIZE=100M
    networks:
      - hotel_net
      
  postgres:
    image: postgres:16-alpine
    container_name: hotel_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_config:/etc/postgresql/postgresql.conf
    networks:
      - hotel_net

  nodejs:
    image: node:22
    container_name: hotel_nodejs
    volumes:
      - ./front:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    tty: true
      
networks:
  hotel_net:
    driver: bridge
    
volumes:
  postgres_data:


